spring:
  application:
    name: loan-scoring

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8090}/realms/${KEYCLOAK_REALM:Hayot}
          principal-claim-name: preferred_username
  r2dbc:
    name: ${PG_DB_NAME:postgres}
    password: ${PG_DB_PASSWORD:postgres}
    username: ${PG_DB_USERNAME:postgres}
    url: r2dbc:postgresql://${PG_HOST:localhost}:${PG_PORT:5432}/${PG_DB_NAME:postgres}
    pool:
      max-life-time: 30s
      enabled: true
      max-idle-time: 1m
      max-size: 500
      initial-size: 50

server:
  port: 8080


services:
  camunda-rest:
    base-url: ${CAMUNDA_REST_BASE_URL:http://172.20.20.135:32123}
    loan-scoring-endpoint: /mobile/microloan/scoring
    webClientProperties:
      maxConnections: 1000
      pendingAcquireMaxCount: 500
      pendingAcquireTimeout: PT10S
      maxIdleTime: PT20S
      maxLifeTime: PT1M
      responseTimeout: PT30S

uz:
  hayotbank:
    commons:
      error:
        decoder:
          maxConnections: '1000'
          responseTimeout: PT30S
          maxLifeTime: PT1M
          url: http://error-decoder:8080/api/decode
          maxIdleTime: PT20S
          pendingAcquireMaxCount: '500'
          pendingAcquireTimeout: PT10S
        unknown:
          code: '-1'
          actor: application

